### ISSUE TITLE
npm run build on react resulted to error

### ISSUE THREAD

**Issue by ljayz** [sd1337/adminlte-2-react#2] opened 2019-03-25 07:58 UTC
After running npm build using react. It successfully generate build folder. Unfortunately running the generated build resulted in error:

Uncaught TypeError: Super expression must either be null or a function, not undefined

**Comment by sd1337** [comment] 2019-03-25 19:41
I've already noticed that too in on of my app's. It is caused by react-dates and the webpack config of create-react-app/react-scripts. Unfortunately the only solutions seems to be to eject cra and add the option ```unused: false``` to the TerserPlugin Configuration

This is found at line 186-227 in webpack.config.js file.
```
        new TerserPlugin({
          terserOptions: {
            parse: {
              // we want terser to parse ecma 8 code. However, we don't want it
              // to apply any minfication steps that turns valid ecma 5 code
              // into invalid ecma 5 code. This is why the 'compress' and 'output'
              // sections only apply transformations that are ecma 5 safe
              // https://github.com/facebook/create-react-app/pull/4234
              ecma: 8,
            },
            compress: {
              ecma: 5,
              warnings: false,
              // Disabled because of an issue with Uglify breaking seemingly valid code:
              // https://github.com/facebook/create-react-app/issues/2376
              // Pending further investigation:
              // https://github.com/mishoo/UglifyJS2/issues/2011
              comparisons: false,
              // Disabled because of an issue with Terser breaking valid code:
              // https://github.com/facebook/create-react-app/issues/5250
              // Pending futher investigation:
              // https://github.com/terser-js/terser/issues/120
              inline: 2,
              unused: false,
            },
            mangle: {
              safari10: true,
            },
            output: {
              ecma: 5,
              comments: false,
              // Turned on because emoji and regex is not minified properly using default
              // https://github.com/facebook/create-react-app/issues/2488
              ascii_only: true,
            },
            unused: false,
          },
          // Use multi-process parallel running to improve the build speed
          // Default number of concurrent runs: os.cpus().length - 1
          parallel: true,
          // Enable file caching
          cache: true,
          sourceMap: shouldUseSourceMap,
        }),
```

**Comment by sd1337** [comment] 2019-03-25 19:43
Sorry for closing the issue. Got the button wrong. If somethings is unclear reopen it. I will add the info in the readme too

**Comment by ljayz** [comment] 2019-03-26 01:22
Ejecting cra and adding the option works . Verified on my end. Thank you very much

**Closed** 2019-03-26 05:49 UTC
